"""Local Toy visual preview. Cloud/rank are clearly labeled in-memory demos only."""
import argparse
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
import tempfile
from urllib.parse import urlsplit

from build_toy import build_toy

PREFIX = "/toy/word-kanji/"
SDK = "https://s1.hdslb.com/bfs/seed/toy/app/sdk/toy-sdk.js"
DEMO = r"""
// Local preview only; this file is generated by the preview server, not published.
(() => {
  const records = {wk_scope_v1:'0'.repeat(32)}, scores = {1:268, 2:196};
  const myName = '本地体验（我）';
  const names = ['青山', '听雨', '晚风', '一叶知秋', '字里行间', '小小猜字家', '南山有木', '慢慢想就会了', '云边的书店', '今天也来猜个字'];
  function rows(board) {
    const items = Array.from({length:99}, (_, i) => ({
      nickname:`${names[i % names.length]}${String(i + 1).padStart(2, '0')}`,
      score:board === 1 ? 580 - Math.floor(i / 2) * 10 : 306 - Math.floor(i / 2) * 5
    }));
    items.push({nickname:myName, score:scores[board] || 0});
    return items.sort((a,b) => b.score-a.score).map((item,i) => ({...item,rank:i+1,avatar:''}));
  }
  window.toy = {
    async getUserProfile() { return { toyOpenId: 'local-preview-only', nickname: myName }; },
    async getCloudStorage() { return { ...records }; },
    async setCloudStorage(items) { Object.assign(records, items); },
    async submitScore({board, score}) { scores[board] = Math.max(scores[board] || 0, score); return {score: scores[board]}; },
    async getRankList({board, limit = 100}) {
      return rows(board).slice(0, limit);
    },
    async getMyRank({board}) {
      const mine = rows(board).find(item => item.nickname === myName);
      return {ranked:!!mine,score:mine?.score || 0,rank:mine?.rank || 0};
    }
  };
})();
"""


def handler(root):
    class PreviewHandler(BaseHTTPRequestHandler):
        def do_GET(self):
            path = urlsplit(self.path).path
            if path in ("/", "/toy/word-kanji"):
                self.send_response(302)
                self.send_header("Location", PREFIX + "index.html")
                self.end_headers()
                return
            name = path.removeprefix(PREFIX) or "index.html"
            if not path.startswith(PREFIX) or "/" in name or "\\" in name or name in (".", ".."):
                self.send_error(404)
                return
            if name == "preview-sdk.js":
                data = DEMO.encode("utf-8")
            else:
                file = root / name
                if not file.is_file() or file.is_symlink():
                    self.send_error(404)
                    return
                data = file.read_bytes()
                if name == "index.html":
                    text = data.decode("utf-8").replace(SDK, "./preview-sdk.js")
                    text = text.replace('<body>', '<body><div class="preview-notice">本地预览 · 云存档和排行榜为模拟数据，未连接 Toy 平台</div>')
                    text = text.replace('</head>', '<style>.preview-notice{position:fixed;bottom:0;left:0;right:0;z-index:20;text-align:center;background:#fff1c7;color:#614713;padding:5px 10px;font:12px/1.5 sans-serif;pointer-events:none}</style></head>')
                    data = text.encode("utf-8")
            content_type = {".js": "text/javascript", ".html": "text/html", ".css": "text/css", ".svg": "image/svg+xml", ".json": "application/json"}.get(Path(name).suffix, "text/plain")
            self.send_response(200)
            self.send_header("Content-Type", content_type + "; charset=utf-8")
            self.send_header("Cache-Control", "no-store")
            self.end_headers()
            self.wfile.write(data)

        def log_message(self, *_args):
            pass
    return PreviewHandler


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--port", type=int, default=8011)
    args = parser.parse_args()
    with tempfile.TemporaryDirectory(prefix="word-kanji-toy-preview-") as directory:
        root = build_toy(directory)
        server = ThreadingHTTPServer(("127.0.0.1", args.port), handler(root))
        print(f"Local demo only: http://127.0.0.1:{args.port}{PREFIX}index.html", flush=True)
        try:
            server.serve_forever()
        except KeyboardInterrupt:
            pass
        finally:
            server.server_close()
